snapcore/core-build

config/lib/systemd/system/snapd.generate-network-conf.service
It predates the current netplan-based solution.
Signed-off-by: Zygmunt Krynicki <zygmunt.krynicki@canonical.com>
=> Remove snapd.generate-network-conf.service

config/etc/sudoers.d/10-ubuntu-core-secure-path
This was merged to the ubuntu sudo package and can be dropped
Signed-off-by: Zygmunt Krynicki <zygmunt.krynicki@canonical.com>
=> Remove 10-ubuntu-core-secure-path

.travis.yml, config/usr/bin/mkswapfile, config/usr/lib/snapd/sshd-host-keygen, initramfs/debian/initramfs-tools-ubuntu-core.postinst, initramfs/scripts/local-premount/resize
- sets up xenial env
- runs shellcheck
- builds two source packages
- builds two binary packages
=> add shellcheck test, fix code for shellcheck

config/etc/system-image/writable-paths
Make /etc/environment writable to allow setting a system wide proxy on UbuntuCore images
=> make /etc/environment writable

config/etc/cloud/cloud.cfg.d/10_snappy.cfg, config/etc/cloud/ds-identify.cfg, config/etc/system-image/writable-paths
- Add cloud-init datasource identify policy (ds-identify.cfg). The policy
configured requires cloud-init systemd generator to detect local
datasource to enable cloud-init, otherwise it will remain disabled.
- Enable cloud-init to use netplan renderer for network configurations
- Update writable-paths to sync /etc/cloud and /etc/cloud.cfg.d which
enables the default configuration of cloud-init in the core image to be
merged with configuration files which are added to the writable
partition.
- Dropped apt_configure configuration, it wasn't correct and cloud-init
now skips running this module if the system it's running on is
Ubuntu Core
=> Update cloud-init configuration

.gitignore, .travis.yml, initramfs/scripts/ubuntu-core-functions, initramfs/testing/Makefile, initramfs/testing/aaa-tests.py, initramfs/testing/helpers.py, initramfs/testing/init.c
This patch adds a number of support files that allows testing initrd
scripts via a high-level language (Python 3).
The main idea is that function-level tests are described in Python and
are executed via qemu on a virtual machine running the desired kernel,
the stock initrd from the core snap and files from the local repository.
The virtual machine is controlled with qemu monitor. A snapshot is taken
just after the machine reaches a stable state (as described by a
particular point in the /init script). Each test commences by
instructing the virtual machine monitor to revert to that snapshot.
Overall performance is excellent, with latency of 1st boot at around two
seconds and latency of snapshot restore close being immeasurable.
Certain amount of shell-level mocking is employed so that …
=> initramfs/testing: add unit tests for initrd scripts

config/etc/cloud/ds-identify.cfg
cloud-init still runs when no local datasource is present unless we ignore maybe datasources (ones that may be populated later during boot).  Core uses strict mode which requires positive identification or cloud-init doesn't run.
=> cloud-init: fix strict mode, ensure cloud-init only runs on positive id

config/etc/system-image/writable-paths
http://manpages.ubuntu.com/manpages/xenial/man5/writable-paths.5.html
synced:
[ Any file appearing in the root filesystem will also be copied
over to writable storage. However file removals are still not
synced  and  files  existing  in both read-only and writeable
storage will not be updated. ]...
transition:
[ ...note that subsequent boots
will ignore any new files appearing or  disappearing  in  the
original  read-only  rootfs  location  unless  you  perform a
factory reset. ]...
=> switch /etc/systemd/system to "synced" mode

initramfs/scripts/local-premount/resize
- we are missing valuable info in the resize logs, so add -p everywhere
- resize2fs fails with the new quoting when $resizeopts is empty (like it was in the GPT case), 
this issue is fixed as a side effect of adding -p everywhere.
=> fix resize for GPT, be more verbose for logging

initramfs/scripts/ubuntu-core-rootfs
The sync_dirs() has a test -e that fails to take broken symlinks
into account. This means that symlinks that are broken when
sync_dir runs (which is a very special environment) are not
copied. This breaks e.g. the symlink snapd.snap-repair.timer
in /etc/systemd/system/timer-target.wants.
This is *not* tested yet, I'm still thinking about the best way to do this.
=> ubuntu-core-rootfs: deal with (broken) symlink in sync_dirs

initramfs/scripts/ubuntu-core-rootfs
We don't want/need to mount the squashfs as RW (which is the default).
=> ubuntu-core-rootfs: mount os/kernel snaps RO

config/debian/changelog, config/etc/system-image/writable-paths
For branding purposes of customers, /etc/update-motd.d needs to be be writable so customers can put extra bits into the login info of the message of the day that is shown right after ssh login.
=> make /etc/update-motd.d writable for branding purposes

initramfs/scripts/local-bottom/fixrtc-mount
The fixrtc script we currently use to work around the issue that
the system clock in incorrect on a system without battery RTC
is not working well because the last mount time is never updated
on xenial systems.
This version of fixrtc-mount will look at the "snaps" directory
to get a more accurate estimate of the system time.
Thanks to Alfonso Sanchez-Beato for the script.
=> scripts: add fixrtc-munt script to fix time issues on pi2,3

initramfs/scripts/ubuntu-core-rootfs
We have code in ubuntu-core-rootfs that processes all mounts in
/etc early. Part of it does a mkdir to create missing mount-points.
However some mounts in /etc are file-based bind mounts
(like /etc/hosts). For those the current code will try to
mkdir /etc/hosts but that fails because the file may exist already.
This PR fixes this error by checking for the existance of the
target only (the previous code was checking for the directory).
=> scripts/ubuntu-core/rootfs: fix mkdir error when the file exists

initramfs/hooks/resize, initramfs/hooks/ubuntu-core-rootfs
Shellcheck on bionic is a bit more strict than on xenial. This should fix the current build failure on bionic of initramfs-tools-ubuntu-core.
=> initramfs: fix shellchecks on bionic

initramfs/testing/helpers.py
When running tests on modern python I got a warning about missing await for async sleep.
Signed-off-by: Zygmunt Krynicki <me@zygoon.pl>
=> tests: fix RuntimeWarning coroutine was never awaited

initramfs/scripts/ubuntu-core-rootfs
We had inherited some code from the ubuntu-phone days to customize
the final system with arbitrary content. We never used this and
we don't have default users anyway so it won't work. Hence remove
this dead code.
=> initramfs: remove dead code

initramfs/scripts/ubuntu-core-functions, initramfs/scripts/ubuntu-core-rootfs
Don't call wait-for-root on device-mapped ubuntu-data to prevent random
delays during the boot process, and remove previous workarounds and
debug code.
=> initramfs: fix delays in installed system boot

initramfs/scripts/local-premount/install
When in install and recover modes we don't want to unmount the ubuntu-data
tmpfs in initramfs (it worked because the filesystem was in use and the
umount command failed).
=> initramfs: remove misplaced umount

initramfs/scripts/ubuntu-core-rootfs
Trivial typo fix: s/requried/required/ in mountroot error messages.
=> ubuntu-core-rootfs: fix typo in error message

initramfs/scripts/local-premount/install, initramfs/scripts/ubuntu-core-rootfs, initramfs/testing/aaa-tests.py
Refactor the installation initramfs script to run chooser at writable
tmpfs creation time. This change requires a new version of chooser
from spike-tools.
Install mode is fully implemented, but recover mode only works with the
system we already booted from. Support to rebooting from a different
version will be added after establishing the boot strategy for current
and next kernels to avoid passing an open variable to the kernel command
line.
=> initramfs: run chooser from initramfs

initramfs/scripts/ubuntu-core-rootfs
Change LUKS device operations to use the master key directly.
=> initramfs: open luks device using the master key

initramfs/scripts/ubuntu-core-rootfs
The master key to the LUKS device containing ubuntu-data is now sealed
to the TPM at installation time. Unseal the key to open the device and
allow access to the data within.
=> initramfs: unseal luks master key

initramfs/scripts/ubuntu-core-functions, initramfs/scripts/ubuntu-core-rootfs, initramfs/testing/aaa-tests.py
Uncomment wait-for-root calls and create /dev/disk/by-label/ubuntu-data
instead by triggering udev. This manual trigger shouldn't be necessary,
so we still need to know what is happening.
=> initramfs: restore wait-for-root calls

initramfs/scripts/local-premount/install
When booting in run mode, check if our magic key has been pressed
and execute some other action in this case.
=> initramfs: check keypress in run mode

initramfs/scripts/local-premount/install, initramfs/scripts/ubuntu-core-rootfs
If the magic trigger key is detected, switch to recover mode. This
requires a state to be set in premount and later recovered in the
rootfs script and in the booted system, so we're creating a
temporary file for this. Sanitize later.
=> initramfs: run recover mode if trigger is detected

initramfs/scripts/local-premount/install, initramfs/scripts/ubuntu-core-rootfs
To make TPM policy generation easier, remove snap parameters such as
snap_core and snap_kernel from the kernel command line and read
them directly from the grub environment file.
=> initramfs: get snap parameters from grubenv

initramfs/scripts/local-premount/install, initramfs/scripts/local-premount/resize, initramfs/scripts/ubuntu-core-rootfs
Use snap_recovery_mode to hold the run mode and reserve snap_mode for
the try, trying modes.
=> initramfs: update run mode variable name

initramfs/scripts/ubuntu-core-rootfs
Update initramfs to call the ubuntu-core-fde-utils unlock utility with
the new parameters from policy-work-3.
=> initramfs: update unlock keyfile parameter

config/etc/system-image/writable-paths
When snapd is installed on a UC16 system it will try to create
files in /etc/systemd/user for the snapd user session agent.
This directory is currently not writable and this PR fixes
this so that we can (eventually) install snapd on UC16.
=> writable-paths: enable create writable /etc/systemd/user

initramfs/Makefile, initramfs/scripts/ubuntu-core-rootfs, initramfs/tests/test_ubuntu-core-rootfs.sh
The new handle_writable_defaults() helper will take the defaults
from $writable/system-data/_writable_defaults/ and apply them on top of
the populated $writable/system-data.
This will allow providing image defaults in a clean way.
This will also get ported to UC20.
=> initramfs: add new handle_writable_defaults()
